name: unimeth
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - unimeth=0.2.3
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - torch==2.5.1+cu124
      - pyslow5>=1.4.0
